/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Kevin
 * Created: 12 déc. 2023
 */

create user voyage with password 'etu001844';
CREATE DATABASE voyage OWNER voyage;
\c voyage;

CREATE TABLE activite (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(256) NOT NULL
);

CREATE TABLE stock_activite_billet(
    id SERIAL PRIMARY KEY,
    id_activite int REFERENCES activite(id) NOT NULL,
    quantite int NOT NULL,
    prix_unitaire int NOT NULL,
    insert_date DATETIME NOT NULL
);

CREATE TABLE bouquet (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(256)
);

CREATE TABLE rel_act_bouquet (
    id SERIAL PRIMARY KEY,
    idActivite INT REFERENCES activite(id),
    idBouquet INT REFERENCES bouquet(id)
);

-- Generated by ChatGPT 
-- Inserting data into the 'activite' table
INSERT INTO activite (nom) VALUES
    ('Concert'),
    ('Museum Visit'),
    ('Sports Event');

-- Inserting data into the 'stock_activite_billet' table
INSERT INTO stock_activite_billet (id_activite, quantite, prix_unitaire, insert_date) VALUES
    (1, 100, 20, '2024-01-11 10:30:00'),
    (2, 50, 15, '2024-01-11 11:45:00'),
    (3, 75, 30, '2024-01-11 14:20:00');

-- Insertion de données dans la table bouquet
INSERT INTO bouquet (nom) VALUES
    ('Bouquet A'),
    ('Bouquet B'),
    ('Bouquet C');

-- Insertion de données dans la table rel_act_bouquet pour créer des relations entre activite et bouquet
INSERT INTO rel_act_bouquet (idActivite, idBouquet) VALUES
    (1, 1), -- Associe l'Activité 1 au Bouquet A
    (1, 2), -- Associe l'Activité 1 au Bouquet B
    (2, 2), -- Associe l'Activité 2 au Bouquet B
    (3, 3); -- Associe l'Activité 3 au Bouquet C

CREATE OR REPLACE VIEW v_act_rel_bouquet AS
SELECT rab.id as rel_id, a.id as act_id, a.nom as act_nom, b.id as bouq_id, b.nom as bouq_nom  FROM rel_act_bouquet rab 
JOIN activite a ON rab.idActivite = a.id 
JOIN bouquet b ON rab.idBouquet = b.id; 

-- Bouquet a partir ny act_id
SELECT bouq_id as id, bouq_nom as nom FROM v_act_rel_bouquet
WHERE act_id = 1;

-- Get act a paritr de bouq_id
SELECT act_id as id, act_nom as nom FROM v_act_rel_bouquet
WHERE bouq_id = 1;


/*
    Author: Tony Mushah
    Created: 19 Dec 2023
*/
CREATE TABLE localite (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(256) NOT NULL
);

CREATE TABLE voyage (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(256) NOT NULL,
    idBouquet int REFERENCES bouquet(id) NOT NULL,
    idLocalite int REFERENCES localite(id) NOT NULL
);

CREATE TABLE reservations(
    id SERIAL PRIMARY KEY,
    id_voyage int REFERENCES voyage(id) NOT NULL,
    quantite int NOT NULL,
    insert_date DATETIME
);

-- Insertion de données dans la table "reservations"
INSERT INTO reservations (id_voyage, quantite, insert_date) VALUES
    (1, 20, '2024-01-11 12:15:00'),
    (2, 15, '2024-01-11 13:30:00'),
    (3, 25, '2024-01-11 15:45:00');


CREATE TABLE duree (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(256) NOT NULL,
    debut INT NOT NULL,
    fin INT NOT NULL 
);

CREATE TABLE activite_voyage(
    id SERIAL PRIMARY KEY,
    idVoyage INT REFERENCES voyage(id) NOT NULL,
    idActivite INT REFERENCES activite(id) NOT NULL,
    nombre INT NOT NULL,
    id_duree INT REFERENCES duree(id) NOT NULL
);

-- Insertion de données dans la table "localite"
INSERT INTO localite (nom) VALUES ('Paris'), ('Londres'), ('New York');

-- Insertion de données dans la table "duree"
INSERT INTO duree (nom, debut, fin) VALUES ('Courte durée', 1, 5), ('Moyenne durée', 6, 10), ('Longue durée', 11, 15);

-- Insertion de données dans la table "voyage"
-- Assurez-vous d'avoir les valeurs idBouquet et idLocalite existantes dans les tables référencées
INSERT INTO voyage (nom, idBouquet, idLocalite) VALUES ('Voyage A', 1, 1), ('Voyage B', 2, 2), ('Voyage C', 3, 3);

-- Insertion de données dans la table "activite_voyage"
-- Insertion de données dans la table "activite_voyage"
INSERT INTO activite_voyage (idVoyage, idActivite, nombre, id_duree) VALUES
    (1, 2, 10, 1), -- Exemple de relation entre le Voyage 1, l'Activité 2, d'une durée de 10 et correspondant à la Durée 1
    (2, 3, 7, 2),  -- Exemple de relation entre le Voyage 2, l'Activité 3, d'une durée de 7 et correspondant à la Durée 2
    (3, 1, 5, 3);  -- Exemple de relation entre le Voyage 3, l'Activité 1, d'une durée de 5 et correspondant à la Durée 3


CREATE VIEW v_bouq_localite_voyage AS
SELECT 
    v.id AS voyage_id, 
    v.nom AS voyage_nom, 
    l.id AS local_id, 
    l.nom As local_nom, 
    b.id AS bouq_id, 
    b.nom AS bouq_nom 
FROM voyage v 
JOIN localite l ON v.idLocalite = l.id
JOIN bouquet b ON v.idBouquet = b.id;


CREATE VIEW v_act_voyage_duree AS
SELECT 
    av.id as act_voyage_id, 
    vblv.*, 
    a.id as act_id, 
    d.id as duree_id, 
    d.nom as duree_nom, 
    d.debut as duree_debu, 
    d.fin as duree_fin, 
    av.nombre as act_v_nombre,
    a.prix_unitaire as act_prix_unitaire
FROM activite_voyage av
JOIN activite a ON av.idActivite = a.id
JOIN v_bouq_localite_voyage vblv ON vblv.voyage_id = av.idVoyage
JOIN duree d ON av.id_duree = d.id;